# make a static claim for Golden Gate
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jf
  name: golden-gate-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/gg
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kub2.local
---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# is-default-class: true
# metadata:
  # name: def
