---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rancher
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jf
  name: golden-gate-vol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "local-storage"
  resources:
    requests:
      storage: 1Mi
  volumeName: golden-gate-pv
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rancher
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
