# apiVersion: v1
# kind: Service
# metadata:
#   name: trader
#   labels:
#     app: trader
# spec:
#   selector:
#     app: trader
#     tier: services
#   type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trader-pv-claim
  labels:
    app: trader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trader
  labels:
    app: trader
spec:
  selector:
    matchLabels:
      app: trader
      tier: services
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trader
        tier: services
    spec:
      containers:
      - image: revmischa/trader-aarch64:latest
        imagePullPolicy: Always
        name: trader
        tty: true
        stdin: true
        env:
        - name: DATABASE_URL
          value: sqlite:////mnt/trader/trader-v1.db
        - name: EXCHG_API_KEY
          valueFrom:
            secretKeyRef:
              name: trader-exchange
              key: api-key
        - name: EXCHG_SECRET
          valueFrom:
            secretKeyRef:
              name: trader-exchange
              key: secret
        - name: EXCHG_SUBACCOUNT
          valueFrom:
            secretKeyRef:
              name: trader-exchange
              key: subaccount
        volumeMounts:
        - name: trader-persistent-storage
          mountPath: /mnt/trader
      volumes:
      - name: trader-persistent-storage
        persistentVolumeClaim:
          claimName: trader-pv-claim
